import "~/styles/globals.css";

import { type Metadata } from "next";
import { auth } from "~/server/auth";
import { redirect } from "next/navigation";
import ChatSidebar from "./ChatSidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  if (!session?.user) {
    return redirect("/");
  }

  return (
    <div className="flex min-h-screen">
      <div>
        <ChatSidebar userName={session.user?.name ?? undefined} />
      </div>
      <div className="flex-1 overflow-auto">{children}</div>
    </div>
  );
}
